CREATE OR REPLACE FUNCTION PRICE_CALCULATOR_DELETE()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $$
DECLARE
    price DOUBLE PRECISION;
BEGIN
        SELECT total_price
        INTO price
        FROM PURCHASE_ORDER as p
        WHERE p.order_id = OLD.order_id;

        UPDATE PURCHASE_ORDER as p
        SET total_price = price - (OLD.unit_product_price * OLD.product_amount)
        WHERE p.order_id = OLD.order_id;
    RETURN OLD;
END;
$$;

CREATE OR REPLACE TRIGGER PRICE_CALC_TRIG_BEFORE_DELETE
BEFORE DELETE ON ORDER_JUNCTION
FOR EACH ROW
EXECUTE FUNCTION PRICE_CALCULATOR_DELETE();
